import = [
    "/home/jakob/.config/alacritty/alacritty-theme/themes/blood_moon.toml"
]

shell = "nu"

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 4

[font]
size = 16

[selection]
save_to_clipboard = true
